### ISSUE TITLE
web.py script error 

### ISSUE THREAD

**Issue by gossterrible** [kimw/shadowsocks-web#1]
Hi,I tried running the web.py file but i feel on the error.Anyway you can help solve this thanks

`root@Vpn2:/home/shadowsocks-web/shadowsocks-web# python web.py --make-config > /                tmp/shadowsocks.json
Traceback (most recent call last):
  File "web.py", line 455, in <module>
    s = json.dumps(common.make_config(), indent=4, sort_keys=True)
  File "/home/shadowsocks-web/shadowsocks-web/common.py", line 284, in make_conf                ig
    conf = json.load(f)
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
`

**Comment by kimw** [comment]
It works fine on my end with Python 2.7.6.

```bash
$ python web.py --make-config > /tmp/shadowsocks.json
$ cat /tmp/shadowsocks.json 
{
    "method": "aes-256-cfb", 
    "password": "1a8PqzH8H3Ouspyp2LKw", 
    "server": "0.0.0.0", 
    "server_port": 8388, 
    "timeout": 300, 
    "web": {
        "base_url": "/ssweb", 
        "cookie_secret": "d5f3cd1a61298fe0443d82735e6add59f4c87e9b4ee5963a21dbe0d45424d2d0", 
        "service_name": "shadowsocks"
    }, 
    "workers": 1
}
```

Maybe you should double check you steps.

**Comment by gossterrible** [comment]
Thanks for your response.I tried setting it up again today but still had some little difficulties with the setup procedure particularly  after installing supervisor .

> The default supervisord config file have some secure insurece. You can make some modification to take care of this issue ;-) All modifications are one change and one add.

Change the 'chmod' option in '[unix_http_server]' section to 0660 instead of default 0700.
Add a new 'chown' option in the same section as in the sample following:
[unix_http_server]
file=/var/run/supervisor.sock
chmod=0660                    ; the default chmod=0700, we changed this option into 0660
chown=supervisor:supervisor   ; superviosor will run as user 'supervisor' and under 'supervisor' group

[supervisord]
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
childlogdir=/var/log/supervisor
directory=/home/supervisor

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[include]
files=/etc/supervisor/conf.d/*.conf

> sorry am new with the comand line and i don't understand if am to create a new file to store all this. I tried running them as seperate comands but i get some errors``root@VPNagain:/home/shadowsocks-web/shadowsocks-web# [unix_http_server]
chown=supervisor:supervisor   ; superviosor will run as user 'supervisor' and under 'supervisor' gr            oup

[supervisord]
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
childlogdir=/var/log/supervisor
directory=/home/supervisor

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[include]
files=/etc/supervisor/conf.d/*.conf[unix_http_server]: command not found
root@VPNagain:/home/shadowsocks-web/shadowsocks-web# file=/var/run/supervisor.sock
root@VPNagain:/home/shadowsocks-web/shadowsocks-web# chmod=0660                    ; the default ch            mod=0700, we changed this option into 0660
The program 'the' is currently not installed. You can install it by typing:
apt install the
root@VPNagain:/home/shadowsocks-web/shadowsocks-web# chown=supervisor:supervisor   ; superviosor wi            ll run as user 'supervisor' and under 'supervisor' group
superviosor: command not found
root@VPNagain:/home/shadowsocks-web/shadowsocks-web#
root@VPNagain:/home/shadowsocks-web/shadowsocks-web# [supervisord]
[supervisord]: command not found
root@VPNagain:/home/shadowsocks-web/shadowsocks-web# logfile=/var/log/supervisor/supervisord.log
root@VPNagain:/home/shadowsocks-web/shadowsocks-web# pidfile=/var/run/supervisord.pid
root@VPNagain:/home/shadowsocks-web/shadowsocks-web# childlogdir=/var/log/supervisor
root@VPNagain:/home/shadowsocks-web/shadowsocks-web# directory=/home/supervisor
root@VPNagain:/home/shadowsocks-web/shadowsocks-web#
root@VPNagain:/home/shadowsocks-web/shadowsocks-web# [rpcinterface:supervisor]
[rpcinterface:supervisor]: command not found
root@VPNagain:/home/shadowsocks-web/shadowsocks-web# supervisor.rpcinterface_factory=supervisor.rpc            interface:make_main_rpcinterface
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface: command not found
root@VPNagain:/home/shadowsocks-web/shadowsocks-web#
root@VPNagain:/home/shadowsocks-web/shadowsocks-web# [supervisorctl]
[supervisorctl]: command not found
root@VPNagain:/home/shadowsocks-web/shadowsocks-web# serverurl=unix:///var/run/supervisor.sock
root@VPNagain:/home/shadowsocks-web/shadowsocks-web#
root@VPNagain:/home/shadowsocks-web/shadowsocks-web# [include]
[include]: command not found
root@VPNagain:/home/shadowsocks-web/shadowsocks-web# files=/etc/supervisor/conf.d/*.conf
root@VPNagain:/home/shadowsocks-web/shadowsocks-web# command=/usr/local/bin/ssserver -c /etc/shadow            socks.json
-c: command not found
root@VPNagain:/home/shadowsocks-web/shadowsocks-web# supervisor.rpcinterface_factory=supervisor.rpc            interface:make_main_rpcinterface
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface: command not found
root@VPNagain:/home/shadowsocks-web/shadowsocks-web# sudo chown -R shadowsocks-web.shadowsocks .
root@VPNagain:/home/shadowsocks-web/shadowsocks-web# sudo pip install tornado
Collecting tornado
  Downloading tornado-4.4.2.tar.gz (460kB)
    100% |████████████████████████████████| 460kB 2.1MB/s
Collecting singledispatch (from tornado)
  Downloading singledispatch-3.4.0.3-py2.py3-none-any.whl
Collecting certifi (from tornado)
  Downloading certifi-2017.1.23-py2.py3-none-any.whl (382kB)
    100% |████████████████████████████████| 389kB 2.8MB/s
Collecting backports_abc>=0.4 (from tornado)
  Downloading backports_abc-0.5-py2.py3-none-any.whl
Collecting six (from singledispatch->tornado)
  Downloading six-1.10.0-py2.py3-none-any.whl
Installing collected packages: six, singledispatch, certifi, backports-abc, tornado
  Running setup.py install for tornado ... done
Successfully installed backports-abc-0.5 certifi-2017.1.23 singledispatch-3.4.0.3 six-1.10.0 tornad            o-4.4.2
root@VPNagain:/home/shadowsocks-web/shadowsocks-web# python web.py --make-config > /tmp/shadowsocks            .json
Traceback (most recent call last):
  File "web.py", line 17, in <module>
    from colorama import Fore
ImportError: No module named colorama
root@VPNagain:/home/shadowsocks-web/shadowsocks-web# pip install
You must give at least one requirement to install (see "pip help install")
root@VPNagain:/home/shadowsocks-web/shadowsocks-web# pip install colorama
Collecting colorama
  Downloading colorama-0.3.7-py2.py3-none-any.whl
Installing collected packages: colorama
Successfully installed colorama-0.3.7
root@VPNagain:/home/shadowsocks-web/shadowsocks-web# python web.py --make-config > /tmp/shadowsocks            .json
root@VPNagain:/home/shadowsocks-web/shadowsocks-web# sudo mv /tmp/shadowsocks.json /etc/shadowsocks            .json
root@VPNagain:/home/shadowsocks-web/shadowsocks-web# sudo chown shadowsocks.shadowsocks /etc/shadow            socks.json
root@VPNagain:/home/shadowsocks-web/shadowsocks-web# sudo chmod 660 /etc/shadowsocks.json
root@VPNagain:/home/shadowsocks-web/shadowsocks-web# command=/usr/bin/python /home/shadowsocks-web/            web.py
-bash: /home/shadowsocks-web/web.py: No such file or directory
root@VPNagain:/home/shadowsocks-web/shadowsocks-web# ls
common.py   controller.py   __init__.py  README.md  TODO.md     userlib.pyc
common.pyc  controller.pyc  Makefile     templates  userlib.py  web.py
root@VPNagain:/home/shadowsocks-web/shadowsocks-web# command=/usr/bin/python /web.py                           -bash: /web.py: No such file or directory
root@VPNagain:/home/shadowsocks-web/shadowsocks-web# command=/usr/bin/python web.py
No command 'web.py' found, did you mean:
 Command 'webspy' from package 'dsniff' (universe)
 Command 'web2py' from package 'python-web2py' (universe)
web.py: command not found
root@VPNagain:/home/shadowsocks-web/shadowsocks-web# command=/usr/bin/python /home/shadowsocks-web/            web.py
-bash: /home/shadowsocks-web/web.py: No such file or directory
root@VPNagain:/home/shadowsocks-web/shadowsocks-web#

Some help on this will be appreciated. Thanks
